# Form implementation generated from reading ui file '.\context_menu_manager.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MenuManager(object):
    def setupUi(self, MenuManager):
        MenuManager.setObjectName("MenuManager")
        MenuManager.resize(344, 66)
        self.centralwidget = QtWidgets.QWidget(parent=MenuManager)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.add_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.add_button.setObjectName("add_button")
        self.gridLayout.addWidget(self.add_button, 1, 0, 1, 1)
        self.remove_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.remove_button.setObjectName("remove_button")
        self.gridLayout.addWidget(self.remove_button, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        MenuManager.setCentralWidget(self.centralwidget)

        self.retranslateUi(MenuManager)
        QtCore.QMetaObject.connectSlotsByName(MenuManager)

    def retranslateUi(self, MenuManager):
        _translate = QtCore.QCoreApplication.translate
        MenuManager.setWindowTitle(_translate("MenuManager", "MainWindow"))
        self.add_button.setText(_translate("MenuManager", "Add \"Extract here\""))
        self.remove_button.setText(_translate("MenuManager", "Remove \"Extract here\""))
        self.label.setText(_translate("MenuManager", "Context menu:"))
